spring: 
  profiles: 
    active: 
    -dev  
--
spring: 
  profiles: dev  
  application:  
    name: study-springcloud-dev  

--
spring: 
  profiles: test   
  application: 
    name: study-springcloud-test  
